version: "3.5"

services:
    nginx:
        container_name: wp-nginx
        image: nginx:latest
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx/:/etc/nginx/conf.d
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./logs/nginx:/var/log/nginx
            - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime
            - ./www:/var/www/html
        networks:
            - wp-stack-net
        restart: always

    mysql:
        container_name: wp-mariadb
        image: mariadb
        volumes:
            - ./mariadb:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1qazxsw2
        networks:
            - wp-stack-net
        restart: always

    wordpress:
        container_name: wp-php-fpm
        image: wordpress:4.9.8-fpm
        volumes:
            - ./www:/var/www/html
            - ./php.ini.d/general.ini:/usr/local/etc/php/conf.d/general.ini
        environment:
            - WORDPRESS_DB_NAME=wpdb
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_PASSWORD=1qazxsw2
        networks:
            - wp-stack-net
        restart: always

networks:
    wp-stack-net:
        driver: bridge
        ipam:
            config:
              - subnet: 10.5.0.0/16
